export interface Facility {
  id: string;
  name: string;
  category: string;
  distance: number; // in meters
  walkingTime: number; // in minutes
  crowdLevel: 'Low' | 'Moderate' | 'Heavy';
  isOpen: boolean;
  openingHours: string;
  accessibilityInfo: string;
  details: string; // location details
  coordinates: { x: number; y: number };
}

export const FACILITY_CATEGORIES = [
  'Washrooms',
  'Accessible Washrooms',
  'ATMs',
  'Water Stations',
  'Charging Stations',
  'Information Desk',
  'First Aid Center',
  'Prayer Room',
  'Merchandise Store',
  'Baby Care Room',
  'Smoking Zone',
  'Lost & Found Counter',
];

export const MOCK_FACILITIES: Facility[] = [
  {
    id: 'facility-washroom-1',
    name: 'Level 1 North Washrooms',
    category: 'Washrooms',
    distance: 60,
    walkingTime: 1,
    crowdLevel: 'Low',
    isOpen: true,
    openingHours: 'Open during match event hours',
    accessibilityInfo: 'Standard washroom facilities.',
    details: 'Level 1 Concourse near Section 114',
    coordinates: { x: 250, y: 460 },
  },
  {
    id: 'facility-washroom-2',
    name: 'Level 2 South Washrooms',
    category: 'Washrooms',
    distance: 220,
    walkingTime: 4,
    crowdLevel: 'Heavy',
    isOpen: true,
    openingHours: 'Open during match event hours',
    accessibilityInfo: 'Standard washroom facilities.',
    details: 'Level 2 Concourse near Section 142',
    coordinates: { x: 300, y: 120 },
  },
  {
    id: 'facility-washroom-accessible-1',
    name: 'Level 1 North Accessible Washrooms',
    category: 'Accessible Washrooms',
    distance: 65,
    walkingTime: 1,
    crowdLevel: 'Low',
    isOpen: true,
    openingHours: 'Open during match event hours',
    accessibilityInfo: 'Fully accessible. Includes baby changing station, grab bars, emergency cord.',
    details: 'Level 1 Concourse near Section 114, ramp access',
    coordinates: { x: 250, y: 465 },
  },
  {
    id: 'facility-atm-1',
    name: 'Chase ATM Section 112',
    category: 'ATMs',
    distance: 110,
    walkingTime: 2,
    crowdLevel: 'Moderate',
    isOpen: true,
    openingHours: '24/7 during events',
    accessibilityInfo: 'Audio-assisted, wheelchair height accessible.',
    details: 'Section 112 Concourse',
    coordinates: { x: 280, y: 480 },
  },
  {
    id: 'facility-atm-2',
    name: 'Capital One ATM Gate D',
    category: 'ATMs',
    distance: 280,
    walkingTime: 5,
    crowdLevel: 'Low',
    isOpen: true,
    openingHours: '24/7 during events',
    accessibilityInfo: 'Audio-assisted, wheelchair height accessible.',
    details: 'Gate D Plaza',
    coordinates: { x: 180, y: 220 },
  },
  {
    id: 'facility-water-1',
    name: 'Hydration Station Sec 122',
    category: 'Water Stations',
    distance: 140,
    walkingTime: 2,
    crowdLevel: 'Low',
    isOpen: true,
    openingHours: 'Open during match event hours',
    accessibilityInfo: 'Accessible drinking fountain & water bottle refill station.',
    details: 'Section 122 Concourse',
    coordinates: { x: 380, y: 430 },
  },
  {
    id: 'facility-charging-1',
    name: 'Charging Zone Sec 108',
    category: 'Charging Stations',
    distance: 180,
    walkingTime: 3,
    crowdLevel: 'Heavy',
    isOpen: true,
    openingHours: 'Open during match event hours',
    accessibilityInfo: 'Seated charging bar with variable height desks.',
    details: 'Section 108 Lounge',
    coordinates: { x: 420, y: 350 },
  },
  {
    id: 'facility-info-1',
    name: 'Guest Information Desk Gate A',
    category: 'Information Desk',
    distance: 190,
    walkingTime: 3,
    crowdLevel: 'Moderate',
    isOpen: true,
    openingHours: 'Gates open until 1 hour post-match',
    accessibilityInfo: 'Assistance headsets available, lower service counter.',
    details: 'Gate A Main Entrance Lobby',
    coordinates: { x: 210, y: 350 },
  },
  {
    id: 'facility-medical-1',
    name: 'First Aid Clinic (Sec 118)',
    category: 'First Aid Center',
    distance: 80,
    walkingTime: 1,
    crowdLevel: 'Low',
    isOpen: true,
    openingHours: 'Open 2 hours pre-match until stadium clears',
    accessibilityInfo: 'Paramedic, doctor, and nurse on duty. Fully accessible facility.',
    details: 'Level 1, Section 118',
    coordinates: { x: 210, y: 430 },
  },
  {
    id: 'facility-prayer-1',
    name: 'Interfaith Prayer Room Sec 132',
    category: 'Prayer Room',
    distance: 220,
    walkingTime: 4,
    crowdLevel: 'Low',
    isOpen: true,
    openingHours: 'Open during all events',
    accessibilityInfo: 'Quiet space, clean seating, shoe storage, wheelchair accessible.',
    details: 'Level 2 Concourse, near Section 132',
    coordinates: { x: 390, y: 260 },
  },
  {
    id: 'facility-store-1',
    name: 'FIFA Official Store Gate C',
    category: 'Merchandise Store',
    distance: 170,
    walkingTime: 3,
    crowdLevel: 'Heavy',
    isOpen: true,
    openingHours: 'Open from stadium opening to 1 hour post-match',
    accessibilityInfo: 'Wide aisles, step-free access.',
    details: 'Gate C Concourse Level',
    coordinates: { x: 350, y: 450 },
  },
  {
    id: 'facility-baby-1',
    name: 'Baby Care Room Sec 140',
    category: 'Baby Care Room',
    distance: 290,
    walkingTime: 5,
    crowdLevel: 'Low',
    isOpen: true,
    openingHours: 'Open during match event hours',
    accessibilityInfo: 'Nursing chairs, diaper stations, microwave, sink. Fully accessible.',
    details: 'Level 2 Concourse, Section 140',
    coordinates: { x: 280, y: 140 },
  },
  {
    id: 'facility-smoking-1',
    name: 'Smoking Zone Patio B',
    category: 'Smoking Zone',
    distance: 250,
    walkingTime: 4,
    crowdLevel: 'Heavy',
    isOpen: false,
    openingHours: 'Closed during match event hours',
    accessibilityInfo: 'Outdoor step-free concrete surface.',
    details: 'Level 1 Plaza, Patio B (Outdoor area)',
    coordinates: { x: 410, y: 400 },
  },
  {
    id: 'facility-lost-found',
    name: 'Lost & Found Section 124',
    category: 'Lost & Found Counter',
    distance: 210,
    walkingTime: 3,
    crowdLevel: 'Moderate',
    isOpen: true,
    openingHours: 'Open during match event hours and 9am-5pm weekdays',
    accessibilityInfo: 'Lower counter for wheelchair accessibility.',
    details: 'Section 124 Guest Services',
    coordinates: { x: 320, y: 460 },
  },
];
