export interface TransportOption {
  id: string;
  name: string;
  type: string;
  travelTime: number; // in minutes
  cost: string; // formatted cost
  costValue: number; // numeric value for recommendation scoring
  isOpen: boolean; // availability status
  crowdLevel: 'Low' | 'Moderate' | 'Heavy';
  departureFrequency: string;
  pickupPoint: string;
  pickupPointId: string;
  operatingHours: string;
  accessibilitySupport: string;
  details: string;
}

export const TRANSPORT_CATEGORIES = [
  'Metro',
  'Shuttle Bus',
  'Public Bus',
  'Taxi',
  'Uber',
  'Walking',
  'Cycling',
  'Parking',
  'Ride Sharing',
];

export const MOCK_TRANSPORT_OPTIONS: TransportOption[] = [
  {
    id: 'trans-metro',
    name: 'MetLife Stadium Station (Line 1)',
    type: 'Metro',
    travelTime: 35,
    cost: '$2.75',
    costValue: 2.75,
    isOpen: true,
    crowdLevel: 'Heavy',
    departureFrequency: 'Every 6 minutes',
    pickupPoint: 'Rail Station Concourse - West Gate Loop',
    pickupPointId: 'pickup-metro',
    operatingHours: 'Open from 3 hours pre-match until 2 hours post-match',
    accessibilitySupport: 'Elevator access to platforms, tactile paving, wheelchair seating.',
    details: 'Direct rapid transit link connecting MetLife Stadium to Secaucus Junction.',
  },
  {
    id: 'trans-shuttle',
    name: 'FIFA Express Shuttle (Park & Ride)',
    type: 'Shuttle Bus',
    travelTime: 15,
    cost: 'Free',
    costValue: 0,
    isOpen: true,
    crowdLevel: 'Moderate',
    departureFrequency: 'Continuous loop (Every 5 mins)',
    pickupPoint: 'Transit Hub - East Plaza',
    pickupPointId: 'pickup-shuttle',
    operatingHours: 'Active from gates open to 1 hour post-event',
    accessibilitySupport: 'Ramp-equipped low-floor shuttle buses, wheelchair securements.',
    details: 'Free shuttle connecting to external stadium auxiliary parking lot H.',
  },
  {
    id: 'trans-pub-bus',
    name: 'NJ Transit Bus 351',
    type: 'Public Bus',
    travelTime: 40,
    cost: '$6.00',
    costValue: 6.0,
    isOpen: true,
    crowdLevel: 'Heavy',
    departureFrequency: 'Every 15 minutes',
    pickupPoint: 'Bus Terminal - South-West Gate Loop',
    pickupPointId: 'pickup-bus',
    operatingHours: 'Matches event schedule, last departure 1 hour post-match',
    accessibilitySupport: 'Kneeling buses, audio announcement system.',
    details: 'Direct NJ Transit service to Port Authority Bus Terminal (NYC).',
  },
  {
    id: 'trans-taxi',
    name: 'MetLife Official Taxi Stand',
    type: 'Taxi',
    travelTime: 25,
    cost: '$25.00+',
    costValue: 25.0,
    isOpen: true,
    crowdLevel: 'Moderate',
    departureFrequency: 'On demand (First come, first served)',
    pickupPoint: 'South-East Plaza Taxi Lane',
    pickupPointId: 'pickup-taxi',
    operatingHours: '24/7 during events',
    accessibilitySupport: 'Standard sedans. Assistance with loading mobility aids available.',
    details: 'Fixed-rate and metered taxi services departing from the designated taxi zone.',
  },
  {
    id: 'trans-uber',
    name: 'Uber Priority Pick-up Zone',
    type: 'Uber',
    travelTime: 20,
    cost: '$30.00+',
    costValue: 30.0,
    isOpen: true,
    crowdLevel: 'Heavy',
    departureFrequency: 'On demand via Uber App',
    pickupPoint: 'South Rideshare Lot (Zone A)',
    pickupPointId: 'pickup-uber',
    operatingHours: '24/7 during event hours',
    accessibilitySupport: 'UberAccess / UberWAV available via app booking.',
    details: 'Official rideshare partner pickup zone. Surcharges may apply during peak post-match crowd hours.',
  },
  {
    id: 'trans-walking',
    name: 'MetLife Pedestrian Concourse',
    type: 'Walking',
    travelTime: 12,
    cost: 'Free',
    costValue: 0,
    isOpen: true,
    crowdLevel: 'Low',
    departureFrequency: 'Self-paced',
    pickupPoint: 'Gate 4 Main Pedestrian Walkway',
    pickupPointId: 'gate-4',
    operatingHours: 'Open during stadium hours',
    accessibilitySupport: 'Step-free wide sidewalks, level surfaces.',
    details: 'Walkway connecting MetLife outer ring to local hotel and plaza parking structures.',
  },
  {
    id: 'trans-cycling',
    name: 'Secured Bicycle Parking Racks',
    type: 'Cycling',
    travelTime: 18,
    cost: 'Free',
    costValue: 0,
    isOpen: true,
    crowdLevel: 'Low',
    departureFrequency: 'Self-paced',
    pickupPoint: 'Bicycle Hub - West Gate',
    pickupPointId: 'pickup-cycling',
    operatingHours: 'Gates open until 2 hours post-match',
    accessibilitySupport: 'Ground-level outdoor bike racks, step-free access.',
    details: 'Secure lockup racks. Please bring your own lock. Helmets can be checked at guest services.',
  },
  {
    id: 'trans-parking',
    name: 'MetLife Parking Lot E',
    type: 'Parking',
    travelTime: 8,
    cost: '$40.00',
    costValue: 40.0,
    isOpen: true,
    crowdLevel: 'Heavy',
    departureFrequency: 'Self-driven',
    pickupPoint: 'North Parking Lot E (Sec 1-10)',
    pickupPointId: 'pickup-parking',
    operatingHours: 'Open 4 hours pre-match until 2 hours post-match',
    accessibilitySupport: 'Dedicated ADA parking slots near the ramp entrance. ADA placard required.',
    details: 'On-site stadium parking lot. Pre-paid parking pass recommended to guarantee spot.',
  },
  {
    id: 'trans-rideshare',
    name: 'General Ride Sharing Zone',
    type: 'Ride Sharing',
    travelTime: 22,
    cost: '$18.00+',
    costValue: 18.0,
    isOpen: false, // Closed temporarily for crowd safety demonstration
    crowdLevel: 'Moderate',
    operatingHours: 'Currently closed for safety management',
    departureFrequency: 'Unavailable',
    pickupPoint: 'South Rideshare Lot (Zone B)',
    pickupPointId: 'pickup-rideshare',
    accessibilitySupport: 'Assisted loading platform available.',
    details: 'Alternative drop-off/pick-up zone for non-partner rideshare services.',
  },
];
